name: 'provider_360'
version: '1.0.0'
config-version: 2
profile: 'provider_360'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dbt_invocation_id: '{{ invocation_id }}'

on-run-start:
  - "{{ log_run_start() }}"

on-run-end:
  - "{{ log_run_end() }}"

seeds:
  provider_360:
    +schema: SEEDS

models:
  provider_360:
    +persist_docs:
      relation: true
      columns: true
    +query_tag: 'dbt_provider_360'
    bronze:
      +materialized: view
      +schema: RAW
      +tags: ['bronze']
    silver:
      +materialized: incremental
      +schema: SILVER
      +on_schema_change: sync_all_columns
      +tags: ['silver']
    gold:
      +materialized: table
      +schema: GOLD
      +on_schema_change: fail
      +tags: ['gold']
    audit:
      +schema: AUDIT
      +tags: ['audit']
      +on_schema_change: append_new_columns
      rejects:
        +schema: REJECT
        +materialized: incremental
        +on_schema_change: append_new_columns
        +tags: ['audit', 'reject']

snapshots:
  provider_360:
    +target_schema: SNAPSHOTS
